name: jjstats
options:
  bundleIdPrefix: sh.saqoo
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.2"
    CURRENT_PROJECT_VERSION: "4"
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  jjstats:
    type: application
    platform: macOS
    sources:
      - path: Sources/jjstats
        excludes:
          - "**/.DS_Store"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: sh.saqoo.jjstats
      PRODUCT_NAME: jjstats
      INFOPLIST_FILE: Sources/jjstats/Info.plist
      GENERATE_INFOPLIST_FILE: false
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: G5G54TCH8W
      ENABLE_HARDENED_RUNTIME: YES
    info:
      path: Sources/jjstats/Info.plist
      properties:
        CFBundleName: jjstats
        CFBundleDisplayName: jjstats
        CFBundleIdentifier: sh.saqoo.jjstats
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        CFBundlePackageType: APPL
        CFBundleExecutable: jjstats
        LSMinimumSystemVersion: "14.0"
        NSHighResolutionCapable: true
        LSApplicationCategoryType: public.app-category.developer-tools
